#!/bin/bash

# Source .env
if [ -f .env ]; then
    set -a
    source .env
    set +a
fi

# Override with any .env.* files
for env in .env.*; do
    if [ -f "$env" ]; then
        set -a
        source "$env"
        set +a
    fi
done

# Run app
uvicorn src.main:app --host $HOST --port $PORT --reload
